# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronaves',
            fields=[
                ('id_aeronave', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_de_assentos', models.IntegerField()),
            ],
            options={
                'db_table': 'aeronaves',
            },
        ),
        migrations.CreateModel(
            name='Aeroportos',
            fields=[
                ('id_aeroporto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aeroportos',
            },
        ),
        migrations.CreateModel(
            name='Aliancas',
            fields=[
                ('id_alianca', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'aliancas',
            },
        ),
        migrations.CreateModel(
            name='Assentos',
            fields=[
                ('id_assento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
                ('id_aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assento_aeronave', to='app.Aeronaves')),
            ],
            options={
                'db_table': 'assentos',
            },
        ),
        migrations.CreateModel(
            name='Chegadas',
            fields=[
                ('id_chegada', models.AutoField(primary_key=True, serialize=False)),
                ('data_chegada', models.DateField()),
                ('hora_chegada', models.TimeField()),
                ('id_aeroporto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chegada_aeroporto', to='app.Aeroportos')),
            ],
            options={
                'db_table': 'chegadas',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('rg', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=20)),
                ('numero_passaporte', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='LinhasAereas',
            fields=[
                ('id_linha_aerea', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('id_alianca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliancas_linhas_aereas', to='app.Aliancas')),
            ],
            options={
                'db_table': 'linhas_aereas',
            },
        ),
        migrations.CreateModel(
            name='Partidas',
            fields=[
                ('id_partida', models.AutoField(primary_key=True, serialize=False)),
                ('data_partida', models.DateField()),
                ('hora_partida', models.TimeField()),
                ('id_aeroporto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida_aeroporto', to='app.Aeroportos')),
            ],
            options={
                'db_table': 'partidas',
            },
        ),
        migrations.CreateModel(
            name='Passagens',
            fields=[
                ('id_passagem', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('data_compra', models.DateTimeField()),
                ('preco_de_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_assento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_assento', to='app.Assentos')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passagem_cliente', to='app.Clientes')),
            ],
            options={
                'db_table': 'passagens',
            },
        ),
        migrations.CreateModel(
            name='Promocoes',
            fields=[
                ('id_promocao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=20)),
                ('data_validade', models.DateField()),
            ],
            options={
                'db_table': 'promocoes',
            },
        ),
        migrations.CreateModel(
            name='Voos',
            fields=[
                ('id_voo', models.AutoField(primary_key=True, serialize=False)),
                ('tempo_estimado', models.IntegerField()),
                ('id_aeronaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voos_aeronaves', to='app.Aeronaves')),
                ('id_chegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voo_chegada', to='app.Chegadas')),
                ('id_linha_aerea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voos_linhas_aereas', to='app.LinhasAereas')),
                ('id_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voo_partida', to='app.Partidas')),
            ],
            options={
                'db_table': 'voos',
            },
        ),
        migrations.AddField(
            model_name='passagens',
            name='id_voo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_voo', to='app.Voos'),
        ),
        migrations.AddField(
            model_name='passagens',
            name='promocoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passagem_promocoes', to='app.Promocoes'),
        ),
    ]
